application: music-tube
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /stylesheets
  static_dir: views/stylesheets

- url: /images
  static_dir: views/images

- url: /scripts
  static_dir: views/scripts

- url: .*
  script: app.app

libraries:
- name: webapp2
  version: "2.5.2"